name = "authfordev-user"
main = "app/worker.ts"
compatibility_date = "2024-05-28"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "DO_USER"
class_name = "DurableObjectUser"

[[durable_objects.bindings]]
name = "DO_CHALLENGE"
class_name = "DurableObjectChallenge"

[[durable_objects.bindings]]
name = "DO_PASSKEY"
class_name = "DurableObjectPasskey"

[[env.test.durable_objects.bindings]]
name = "DO_USER"
class_name = "DurableObjectUser"

[[env.test.durable_objects.bindings]]
name = "DO_CHALLENGE"
class_name = "DurableObjectChallenge"

[[env.test.durable_objects.bindings]]
name = "DO_PASSKEY"
class_name = "DurableObjectPasskey"

[env.test.vars]
ENVIRONMENT = "test"
AUDIENCE = "audience"
SECRET_KEY = "secret"

[[migrations]]
tag = "v1"
new_classes = [
    "DurableObjectUser",
    "DurableObjectChallenge",
    "DurableObjectPasskey",
]
