#:schema node_modules/wrangler/config-schema.json
name = "unlock"
main = "./dist/main.js"
build.command = "pnpm build"
build.watch_dir = "app"
compatibility_date = "2024-10-18"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./dist/", binding = "ASSETS" }

[vars]
ORIGIN = "https://unlock.horrible.workers.dev"

[[durable_objects.bindings]]
name = "OBJECT_PASSKEY"
class_name = "DurableObjectPasskey"

[[durable_objects.bindings]]
name = "OBJECT_USER"
class_name = "DurableObjectUser"


[[migrations]]
tag = "v1"
new_sqlite_classes = ["DurableObjectPasskey", "DurableObjectUser"]
